spring:
   application:
      name: springcloud-gateway-zuul
server:
   port: 8040
#eureka客户端连接配置
eureka:
   client:
      service-url:
         #注册中心地址
         defaultZone: http://user:password123@localhost:8761/eureka/
   instance:
      #将ip注册到eureka上
      prefer-ip-address: true
#开启routes节点
management:
   endpoints:
      web:
         exposure:
            include: routes